/* SCIENCE_AUTHORING_EDITOR_START — private drafts, shared protected registration. */
(function () {
    'use strict';
    const TYPES={text:'설명',image:'이미지',choice:'객관식',number:'숫자 답안',short:'서술형',table:'자료 표',circuit:'회로 그림'};
    const MODES={lesson:'수업 자료',exam:'문제풀이',activity:'탐구 활동'};
    const QUESTIONS=new Set(['choice','number','short']);
    const MAX_HTML=3*1024*1024, MAX_IMAGE=700*1024;
    const scriptBase=new URL('.',document.currentScript?.src || document.baseURI);
    let host=null,core=null,runtimeCode=null,corePromise=null;
    let state=freshState();
    const token=()=>typeof getAdminSessionToken==='function'?String(getAdminSessionToken()||''):'';
    const uid=()=>crypto.randomUUID();
    const bid=()=> 'b_'+uid().replace(/-/g,'');
    const clone=v=>JSON.parse(JSON.stringify(v));
    const fingerprint=(source,policy)=>JSON.stringify({source,policy});
    const el=id=>host?.querySelector('#ae'+id);
    const text=v=>v==null?'':String(v);
    const esc=v=>text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    function freshState(){return{mounted:false,auth:'',generation:0,source:null,policy:null,revision:0,selected:null,dirty:false,busy:false,capable:false,unknown:null,requests:new Set(),watch:null,urls:new Set()};}
    function defaultPolicy(){return{enabled:false,printCenter:false,studentPrint:false,points:{mode:'none',amount:0,tiers:[]}};}
    function block(type){const b={id:bid(),type,title:'',body:''};if(type==='image')Object.assign(b,{src:'',alt:'',caption:''});if(type==='choice')Object.assign(b,{options:[{id:'o1',text:''},{id:'o2',text:''},{id:'o3',text:''},{id:'o4',text:''}],correct:'',points:5,required:true,explanation:''});if(type==='number')Object.assign(b,{answer:0,tolerance:0,unit:'',points:5,required:true,explanation:''});if(type==='short')Object.assign(b,{modelAnswer:'',points:5,required:true,explanation:''});if(type==='table')Object.assign(b,{headers:['항목','값'],rows:[['',''],['','']]});if(type==='circuit')Object.assign(b,{layout:'series',voltage:12,resistors:[2,4]});return b;}
    function source(mode='lesson'){const d={format:'science-authoring',version:1,id:uid(),title:'',description:'',mode,blocks:[]};if(mode==='lesson')d.blocks=['도입','탐구','정리'].map(t=>({...block('text'),title:t}));if(mode==='activity')d.blocks=[{...block('text'),title:'활동 안내'},{...block('short'),title:'관찰한 내용을 기록해 보세요.'}];return d;}
    function say(message,kind=''){const n=el('Message');if(n){n.textContent=message;n.dataset.kind=kind;}}
    function validAuth(){if(!state.mounted||!state.auth||state.auth!==token()){if(state.mounted)dispose();return false;}return true;}
    function current(gen){return state.mounted&&state.generation===gen&&validAuth();}
    function selected(){return state.source?.blocks.find(b=>b.id===state.selected);}
    function touch(){state.dirty=true;el('Saved').textContent='저장하지 않은 변경';el('PreviewNote').textContent='내용을 바꾼 뒤 미리보기를 다시 눌러 확인하세요.';renderOutline();}
    function busy(value){state.busy=value;renderBusy();}
    function renderBusy(){if(!host)return;host.setAttribute('aria-busy',String(state.busy));host.querySelectorAll('button,input,select,textarea').forEach(n=>n.disabled=state.busy||!core);if(el('Save'))el('Save').disabled=state.busy||!core||!state.capable||!!state.unknown;if(el('DraftLoad'))el('DraftLoad').disabled=state.busy||!state.capable||!el('Drafts')?.value;el('Reconcile').hidden=!state.unknown;if(el('Reconcile'))el('Reconcile').disabled=state.busy;const b=selected();if(b){el('MoveUp').disabled=state.busy||state.source.blocks.indexOf(b)===0;el('MoveDown').disabled=state.busy||state.source.blocks.indexOf(b)===state.source.blocks.length-1;}if(!state.capable){el('Drafts').disabled=true;el('DraftRefresh').disabled=state.busy;}if(state.source?.blocks.length>=100)el('Add').disabled=true;
        if(b?.type==='choice'){host.querySelectorAll('[data-remove-option]').forEach(n=>n.disabled=state.busy||b.options.length<=2);host.querySelector('[data-add-option]').disabled=state.busy||b.options.length>=8;}
        if(b?.type==='table'){host.querySelectorAll('[data-remove-row]').forEach(n=>n.disabled=state.busy||b.rows.length<=1);host.querySelectorAll('[data-remove-col]').forEach(n=>n.disabled=state.busy||b.headers.length<=1);host.querySelector('[data-add-row]').disabled=state.busy||b.rows.length>=30;host.querySelector('[data-add-col]').disabled=state.busy||b.headers.length>=10;}}

    async function api(action,body={}){if(!validAuth())throw new Error('최고관리자로 다시 로그인해 주세요.');const auth=state.auth,gen=state.generation,base=text(window.PLATFORM_CONFIG?.baseUrl);if(!/^https:\/\/[^/]+\.supabase\.co\/?$/.test(base))throw new Error('플랫폼 서버 주소를 확인할 수 없습니다.');const controller=new AbortController();state.requests.add(controller);const timer=setTimeout(()=>controller.abort(),40000);try{const response=await fetch(base.replace(/\/$/,'')+'/functions/v1/authoring-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,adminKey:auth,...body}),signal:controller.signal,credentials:'omit'});let data;try{data=await response.json();}catch(_){throw new Error('응답을 읽지 못했습니다.');}if(!current(gen))throw new Error('관리자 인증이 변경되었습니다.');if(!response.ok||data?.success!==true){const e=new Error(data?.message||data?.error||'요청을 처리하지 못했습니다.');e.code=data?.code;e.status=response.status;if(response.status===401||response.status===403){const target=host;dispose();if(target)target.textContent='최고관리자 인증을 다시 확인해 주세요. 작성 중인 내용은 화면에서 지웠습니다.';}throw e;}return data;}catch(e){if(e.name==='AbortError')throw new Error('응답을 확인하지 못했습니다. 연결 상태를 확인해 주세요.');throw e;}finally{clearTimeout(timer);state.requests.delete(controller);}}
    async function loadCore(){if(!corePromise)corePromise=import(new URL('authoring-core.mjs',scriptBase).href);try{core=await corePromise;return core;}catch(e){corePromise=null;throw new Error('제작기 공통 파일을 읽지 못했습니다. 페이지를 새로고침해 주세요.');}}
    async function runtime(){if(runtimeCode!==null)return runtimeCode;const gen=state.generation,controller=new AbortController();state.requests.add(controller);const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(new URL('authoring-runtime.js',scriptBase),{credentials:'omit',signal:controller.signal});if(!r.ok)throw new Error('학생 화면 파일을 읽지 못했습니다.');const code=await r.text();if(!current(gen))throw new Error('제작 화면이 닫혔습니다.');if(!code.includes('ScienceAuthoringRuntime'))throw new Error('학생 화면 파일을 확인할 수 없습니다.');runtimeCode=code;return code;}finally{clearTimeout(timer);state.requests.delete(controller);}}
    function mountMarkup(){host.classList.add('authoring-editor');host.innerHTML=`<div class="ae-intro"><div><h4>수업·문제 제작</h4><p>내용을 직접 작성하고, 기존 디자인의 HTML로 저장합니다.</p></div><span id="aeSaved" class="ae-save-state">새 초안</span></div>
    <div class="ae-toolbar"><label class="ae-compact">새 자료 형태<select id="aeNewMode"><option value="lesson">수업 자료</option><option value="exam">문제풀이</option><option value="activity">탐구 활동</option></select></label><button type="button" id="aeNew">새로 만들기</button><button type="button" id="aeImport">HTML 가져오기</button><input id="aeImportFile" type="file" accept=".html,text/html" hidden></div>
    <details class="ae-drafts"><summary>내 제작 자료 불러오기</summary><div class="ae-draft-row"><label>저장한 초안<select id="aeDrafts"><option value="">목록을 읽고 있습니다.</option></select></label><button type="button" id="aeDraftRefresh">목록 새로고침</button><button type="button" id="aeDraftLoad">불러오기</button></div><p class="ae-note">초안은 최고관리자 계정으로 서버에 저장됩니다. HTML 가져오기는 이 제작기로 만든 원본을 지원합니다.</p></details>
    <p id="aeMessage" class="ae-message" role="status" aria-live="polite" aria-atomic="true"></p>
    <div class="ae-document"><label>자료 제목<input id="aeTitle" maxlength="200" placeholder="예: 전압·전류·저항 연습" data-source-field="title"></label><label>짧은 설명<textarea id="aeDescription" rows="2" maxlength="3000" data-source-field="description" placeholder="학생에게 안내할 내용을 적어 주세요."></textarea></label><label class="ae-mode">자료 형태<select id="aeMode" data-source-field="mode"><option value="lesson">수업 자료</option><option value="exam">문제풀이</option><option value="activity">탐구 활동</option></select></label></div>
    <div class="ae-workspace"><aside class="ae-outline"><div class="ae-outline-head"><strong>내용 순서</strong><span id="aeCount"></span></div><ol id="aeOutline" aria-label="편집할 내용"></ol><div class="ae-add"><label for="aeBlockType" class="ae-sr">추가할 내용 유형</label><select id="aeBlockType">${Object.entries(TYPES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button type="button" id="aeAdd">+ 추가</button></div><p class="ae-note">순서를 선택해 편집합니다. 위·아래 이동과 복제를 사용할 수 있습니다.</p></aside><section class="ae-block-panel" aria-label="내용 편집"><div id="aeBlock"></div></section></div>
    <details class="ae-preview" id="aePreviewWrap"><summary>학생 화면 미리보기</summary><p id="aePreviewNote" class="ae-note">현재 내용으로 미리보기를 생성하세요. 여기서 작성한 답안은 제출되지 않습니다.</p><button type="button" id="aePreview">미리보기 새로고침</button><iframe id="aePreviewFrame" title="학생 화면 미리보기" sandbox="allow-scripts" referrerpolicy="no-referrer" hidden></iframe></details>
    <div class="ae-footer"><div><p class="ae-note">자료 등록 화면에서 제출·인쇄·포인트 옵션을 선택합니다.</p><label class="ae-filename">내보낼 파일명<input id="aeFileName" autocomplete="off" maxlength="120" value="science_lesson.html"></label></div><div class="ae-actions"><button type="button" id="aeSave">초안 저장</button><button type="button" id="aeExport">HTML 다운로드</button><button type="button" id="aeRegister" class="ae-primary">자료 등록으로 보내기</button><button type="button" id="aeReconcile" hidden>앞선 저장 결과 확인</button></div></div>`;
    host.addEventListener('input',onInput);host.addEventListener('change',onChange);host.addEventListener('click',onClick);el('New').addEventListener('click',newDocument);el('Add').addEventListener('click',addBlock);el('Import').addEventListener('click',()=>el('ImportFile').click());el('ImportFile').addEventListener('change',importFile);el('Save').addEventListener('click',saveDraft);el('Export').addEventListener('click',()=>exportHTML(false));el('Register').addEventListener('click',()=>exportHTML(true));el('Preview').addEventListener('click',preview);el('DraftRefresh').addEventListener('click',connect);el('DraftLoad').addEventListener('click',loadDraft);el('Drafts').addEventListener('change',renderBusy);el('Reconcile').addEventListener('click',reconcile);}
    function render(){if(!state.source)return;el('Title').value=state.source.title;el('Description').value=state.source.description;el('Mode').value=state.source.mode;renderOutline();renderBlock();renderBusy();}
    function renderOutline(){if(!state.source)return;el('Count').textContent=state.source.blocks.length+'/100';el('Outline').innerHTML=state.source.blocks.length?state.source.blocks.map((b,i)=>`<li><button type="button" data-select="${esc(b.id)}" ${state.selected===b.id?'aria-current="true"':''}><span class="ae-index">${i+1}</span><span class="ae-outline-copy"><small>${TYPES[b.type]}</small><span>${esc(b.title||'제목 없는 '+TYPES[b.type])}</span></span></button></li>`).join(''):'<li class="ae-empty">설명이나 문제를 추가해 주세요.</li>';}
    function field(label,key,value,{type='text',rows=3,min,max,step='any',maxLength=10000,placeholder=''}={}){const attrs=`data-block-field="${key}" ${min!==undefined?'min="'+min+'"':''} ${max!==undefined?'max="'+max+'"':''}`;return `<label>${label}${type==='textarea'?`<textarea ${attrs} rows="${rows}" maxlength="${maxLength}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`:`<input ${attrs} type="${type}" ${type==='number'?'step="'+step+'"':''} maxlength="${maxLength}" value="${esc(value)}" placeholder="${esc(placeholder)}">`}</label>`;}
    function renderBlock(){const b=selected();if(!b){el('Block').innerHTML='<div class="ae-empty"><h4>내용을 추가해 시작하세요.</h4><p>설명과 문제를 원하는 순서로 구성할 수 있습니다.</p></div>';return;}let fields=field('제목 / 질문','title',b.title,{maxLength:200})+field('내용 / 문제의 조건','body',b.body,{type:'textarea',rows:4});
    if(b.type==='image')fields+=`<label>이미지 파일<input type="file" id="aeImage" accept="image/png,image/jpeg,image/webp"></label><p class="ae-note">PNG·JPG·WebP · 최대 700 KB. 이미지는 HTML에 함께 저장됩니다.</p>${b.src?`<img class="ae-image" src="${esc(b.src)}" alt="${esc(b.alt||'편집 중인 이미지')}">`:''}`+field('이미지 설명 (대체 텍스트)','alt',b.alt,{maxLength:500})+field('캡션 / 출처','caption',b.caption,{type:'textarea',rows:2,maxLength:3000});
    if(b.type==='choice')fields+=`<fieldset class="ae-options"><legend>보기와 정답</legend>${b.options.map((o,i)=>`<div class="ae-option"><label class="ae-correct"><input type="radio" name="aeCorrect" data-correct="${esc(o.id)}" ${o.id===b.correct?'checked':''}><span>${i+1}번 정답</span></label><label class="ae-option-text"><span class="ae-sr">${i+1}번 보기</span><input data-option="${esc(o.id)}" maxlength="2000" value="${esc(o.text)}" placeholder="보기 내용"></label><button type="button" data-remove-option="${esc(o.id)}" aria-label="${i+1}번 보기 삭제" ${b.options.length<=2?'disabled':''}>×</button></div>`).join('')}<button type="button" data-add-option ${b.options.length>=8?'disabled':''}>+ 보기 추가</button></fieldset>`;
    if(b.type==='number')fields+=`<div class="ae-grid">${field('정답','answer',b.answer,{type:'number'})}${field('허용 오차 (±)','tolerance',b.tolerance,{type:'number',min:0})}${field('단위','unit',b.unit,{maxLength:30,placeholder:'예: A, V, Ω'})}</div><p class="ae-note">숫자와 지정한 허용 오차로 채점합니다. 단위는 답안 입력칸 옆에 표시됩니다.</p>`;
    if(b.type==='short')fields+=field('교사용 모범답안','modelAnswer',b.modelAnswer,{type:'textarea',rows:4})+'<p class="ae-note">서술형은 교사가 제출 관리에서 점수를 확인합니다. 모범답안과 글자가 같은지 비교하여 자동 채점하지 않습니다.</p>';
    if(QUESTIONS.has(b.type))fields+=`<div class="ae-scoring">${field('배점','points',b.points,{type:'number',min:0,max:100,step:1})}<label class="ae-check"><input type="checkbox" data-block-check="required" ${b.required?'checked':''}>필수 응답</label></div>`+field('제출 후 해설','explanation',b.explanation,{type:'textarea',rows:3});
    if(b.type==='table')fields+=`<p class="ae-note">자료를 보여 주는 표입니다. 학생이 답을 쓰는 칸은 서술형 문항으로 추가하세요.</p><div class="ae-table-scroll"><table class="ae-table"><thead><tr>${b.headers.map((h,c)=>`<th><label><span class="ae-sr">${c+1}열 제목</span><input data-header="${c}" value="${esc(h)}" maxlength="200"></label><button type="button" data-remove-col="${c}" aria-label="${c+1}열 삭제" ${b.headers.length<=1?'disabled':''}>열 삭제</button></th>`).join('')}<th></th></tr></thead><tbody>${b.rows.map((row,r)=>`<tr>${row.map((v,c)=>`<td><label><span class="ae-sr">${r+1}행 ${c+1}열</span><input data-cell="${r},${c}" value="${esc(v)}" maxlength="2000"></label></td>`).join('')}<td><button type="button" data-remove-row="${r}" aria-label="${r+1}행 삭제" ${b.rows.length<=1?'disabled':''}>×</button></td></tr>`).join('')}</tbody></table></div><div class="ae-inline-actions"><button type="button" data-add-row>+ 행 추가</button><button type="button" data-add-col>+ 열 추가</button></div>`;
    if(b.type==='circuit')fields+=`<div class="ae-grid"><label>회로 형태<select data-block-field="layout"><option value="single" ${b.layout==='single'?'selected':''}>저항 1개</option><option value="series" ${b.layout==='series'?'selected':''}>직렬연결</option><option value="parallel" ${b.layout==='parallel'?'selected':''}>병렬연결</option></select></label>${field('전원 전압 (V)','voltage',b.voltage,{type:'number',min:0})}${b.resistors.map((r,i)=>`<label>저항 ${i+1} (Ω)<input type="number" min="0.001" step="any" data-resistor="${i}" value="${esc(r)}"></label>`).join('')}</div><p class="ae-note">회로 그림 아래에 숫자 답안이나 객관식 문항을 추가할 수 있습니다. 학생이 선을 직접 연결하는 활동은 기존 회로 연습실을 이용하세요.</p>`;
    el('Block').innerHTML=`<div class="ae-block-top"><span class="ae-kind">${TYPES[b.type]}</span><div class="ae-inline-actions"><button type="button" id="aeMoveUp" data-move="-1" aria-label="이 내용을 위로 이동">↑</button><button type="button" id="aeMoveDown" data-move="1" aria-label="이 내용을 아래로 이동">↓</button><button type="button" data-clone>복제</button><button type="button" data-remove-block class="ae-danger">삭제</button></div></div><div class="ae-fields">${fields}</div>`;renderBusy();}
    function onInput(e){if(state.busy||!validAuth())return;const n=e.target;if(n.dataset.sourceField){state.source[n.dataset.sourceField]=n.value;touch();return;}const b=selected();if(!b)return;if(n.dataset.blockField){const k=n.dataset.blockField;b[k]=n.type==='number'?(n.value===''?'':Number(n.value)):n.value;touch();}if(n.dataset.option){const o=b.options?.find(o=>o.id===n.dataset.option);if(o){o.text=n.value;touch();}}if(n.dataset.header!==undefined){b.headers[Number(n.dataset.header)]=n.value;touch();}if(n.dataset.cell){const [r,c]=n.dataset.cell.split(',').map(Number);b.rows[r][c]=n.value;touch();}if(n.dataset.resistor!==undefined){b.resistors[Number(n.dataset.resistor)]=n.value===''?'':Number(n.value);touch();}}
    function onChange(e){if(state.busy||!validAuth())return;const n=e.target,b=selected();if(n.id==='aeImage'){readImage(n.files?.[0]);return;}if(!b)return;if(n.dataset.correct){b.correct=n.dataset.correct;touch();}if(n.dataset.blockCheck){b[n.dataset.blockCheck]=n.checked;touch();}if(n.dataset.blockField==='layout'){b.layout=n.value;b.resistors=n.value==='single'?[b.resistors[0]??1]:[b.resistors[0]??1,b.resistors[1]??1];touch();renderBlock();}}
    function onClick(e){const n=e.target.closest('button');if(!n||!host.contains(n)||state.busy||!validAuth())return;if(n.dataset.select){state.selected=n.dataset.select;renderOutline();renderBlock();return;}const b=selected();if(!b)return;let renderNeeded=false;
    if(n.dataset.move){const i=state.source.blocks.indexOf(b),j=i+Number(n.dataset.move);if(j>=0&&j<state.source.blocks.length){[state.source.blocks[i],state.source.blocks[j]]=[state.source.blocks[j],state.source.blocks[i]];renderNeeded=true;}}
    if(n.hasAttribute('data-clone')){if(state.source.blocks.length>=100){say('내용은 최대 100개까지 추가할 수 있습니다.','error');return;}const copied=clone(b);copied.id=bid();state.source.blocks.splice(state.source.blocks.indexOf(b)+1,0,copied);state.selected=copied.id;renderNeeded=true;}
    if(n.hasAttribute('data-remove-block')){if(!window.confirm('선택한 내용을 삭제할까요?'))return;const i=state.source.blocks.indexOf(b);state.source.blocks.splice(i,1);state.selected=state.source.blocks[Math.min(i,state.source.blocks.length-1)]?.id||null;renderNeeded=true;}
    if(n.hasAttribute('data-add-option')&&b.options?.length<8){let i=1;while(b.options.some(o=>o.id==='o'+i))i++;b.options.push({id:'o'+i,text:''});renderNeeded=true;}
    if(n.dataset.removeOption&&b.options?.length>2){b.options=b.options.filter(o=>o.id!==n.dataset.removeOption);if(b.correct===n.dataset.removeOption)b.correct='';renderNeeded=true;}
    if(n.hasAttribute('data-add-row')&&b.rows?.length<30){b.rows.push(b.headers.map(()=>''));renderNeeded=true;}
    if(n.hasAttribute('data-add-col')&&b.headers?.length<10){b.headers.push('항목');b.rows.forEach(r=>r.push(''));renderNeeded=true;}
    if(n.dataset.removeRow!==undefined&&b.rows?.length>1){b.rows.splice(Number(n.dataset.removeRow),1);renderNeeded=true;}
    if(n.dataset.removeCol!==undefined&&b.headers?.length>1){const c=Number(n.dataset.removeCol);b.headers.splice(c,1);b.rows.forEach(r=>r.splice(c,1));renderNeeded=true;}
    if(renderNeeded){touch();renderBlock();}}
    function canLeave(){if(!state.mounted)return true;if(state.busy){say('진행 중인 작업이 끝난 뒤 이동해 주세요.','warning');return false;}if(state.unknown){say('앞선 저장 결과를 확인하거나 HTML을 다운로드한 뒤 이동해 주세요.','warning');return window.confirm('저장 결과가 확인되지 않았습니다. 초안 목록에서 결과를 다시 확인할 수 있습니다. 제작 화면을 닫을까요?');}return !state.dirty||window.confirm('저장하지 않은 변경이 있습니다. 초안 저장 또는 HTML 다운로드로 보관할 수 있습니다. 변경 내용을 닫고 이동할까요?');}
    function setDocument(doc,policy,revision=0){state.source=clone(doc);state.policy=clone(policy);state.revision=revision;state.selected=doc.blocks[0]?.id||null;state.dirty=false;state.unknown=null;el('Saved').textContent=revision?'서버 저장본 · '+revision+'번째 저장':'새 초안';el('FileName').value='science_'+doc.id.slice(0,8)+'.html';el('PreviewFrame').removeAttribute('srcdoc');el('PreviewFrame').hidden=true;render();}
    function newDocument(){if(state.busy||!validAuth()||!canLeave())return;setDocument(source(el('NewMode').value),defaultPolicy());say('새 자료를 만들었습니다. 제목을 입력하고 내용을 추가하세요.');}
    function addBlock(){if(state.busy||!validAuth()||state.source.blocks.length>=100)return;const b=block(el('BlockType').value);state.source.blocks.push(b);state.selected=b.id;touch();renderBlock();el('Block').querySelector('[data-block-field="title"]')?.focus();}
    async function readImage(file){if(!file)return;const gen=state.generation,id=state.selected;if(file.size>MAX_IMAGE||!['image/png','image/jpeg','image/webp'].includes(file.type)){say('PNG·JPG·WebP 이미지(700 KB 이하)를 선택해 주세요.','error');return;}busy(true);try{const bytes=new Uint8Array(await file.arrayBuffer());const valid=file.type==='image/png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:file.type==='image/jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:bytes[0]===82&&bytes[1]===73&&bytes[2]===70&&bytes[3]===70&&bytes[8]===87&&bytes[9]===69&&bytes[10]===66&&bytes[11]===80;if(!valid)throw new Error('이미지 형식과 파일 내용이 일치하지 않습니다.');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));if(!current(gen)||state.selected!==id)return;selected().src='data:'+file.type+';base64,'+btoa(binary);touch();renderBlock();say('이미지를 넣었습니다. 이미지 설명과 출처도 작성해 주세요.');}catch(e){if(current(gen))say(e.message,'error');}finally{if(current(gen))busy(false);}}
    async function importFile(){const input=el('ImportFile'),file=input.files?.[0];input.value='';if(!file||state.busy||!validAuth()||!canLeave())return;if(file.size>MAX_HTML){say('HTML은 3 MiB 이하 파일을 선택하세요.','error');return;}const gen=state.generation;busy(true);try{const html=await file.text();if(!current(gen))return;const parsed=core.extractAuthoring(html);if(!parsed)throw new Error('이 제작기로 만든 전체 HTML 원본을 선택해 주세요. 일반 HTML과 보호용 연결 파일은 편집용 가져오기를 지원하지 않습니다.');const doc=core.validateSource(parsed.source),policy=core.validatePolicy(parsed.policy);doc.id=uid();setDocument(doc,policy);state.dirty=true;el('Saved').textContent='가져온 자료 · 저장 전';el('FileName').value=file.name;say('새 초안으로 가져왔습니다. 원래 등록 자료와 저장한 초안을 덮어쓰지 않습니다.');}catch(e){if(current(gen))say(e.message,'error');}finally{if(current(gen))busy(false);}}
    async function connect(){if(state.busy||!validAuth())return;const gen=state.generation;busy(true);say('초안 저장 기능을 확인하고 있습니다.');try{const conf=await api('config');if(!current(gen))return;state.capable=conf.version===1&&conf.capabilities?.drafts===true;if(!state.capable)throw new Error('이 서버는 제작 초안 저장을 지원하지 않습니다. HTML 다운로드는 사용할 수 있습니다.');await listDrafts();if(current(gen))say('내용을 편집한 뒤 초안 저장 또는 HTML 다운로드로 보관하세요.');}catch(e){if(current(gen)){state.capable=false;say(e.message,'warning');el('Drafts').innerHTML='<option value="">서버 연결을 다시 확인해 주세요.</option>';}}finally{if(current(gen))busy(false);}}
    async function listDrafts(){const data=await api('draft_list');if(!Array.isArray(data.items))throw new Error('초안 목록을 확인할 수 없습니다.');const previous=el('Drafts')?.value;el('Drafts').innerHTML='<option value="">'+(data.items.length?'저장한 자료 선택':'저장한 초안이 없습니다.')+'</option>';for(const item of data.items){const option=document.createElement('option');option.value=item.id;option.textContent=item.title+' · '+(Number.isFinite(Date.parse(item.updatedAt))?new Date(item.updatedAt).toLocaleDateString('ko-KR'):'저장됨');el('Drafts').append(option);}if(previous)el('Drafts').value=previous;}
    async function loadDraft(){if(state.busy||!validAuth()||!el('Drafts').value||!canLeave())return;const gen=state.generation,id=el('Drafts').value;busy(true);say('초안을 불러오고 있습니다.');try{const data=await api('draft_get',{id});if(!current(gen))return;const d=data.draft;if(!d||d.id!==id||!Number.isInteger(d.revision)||d.revision<1)throw new Error('초안 저장본을 확인할 수 없습니다.');const doc=core.validateSource(d.source),policy=core.validatePolicy(d.policy);if(doc.id!==id)throw new Error('초안 식별자가 일치하지 않습니다.');setDocument(doc,policy,d.revision);say('저장한 초안을 불러왔습니다.');}catch(e){if(current(gen))say(e.message,'error');}finally{if(current(gen))busy(false);}}
    function validated(){return{source:core.validateSource(clone(state.source)),policy:core.validatePolicy(clone(state.policy))};}
    async function saveDraft(){if(state.busy||!state.capable||state.unknown||!validAuth())return;let candidate;try{candidate=validated();}catch(e){say(e.message,'error');return;}const gen=state.generation,expectedRevision=state.revision,id=candidate.source.id;busy(true);say('초안을 저장하고 있습니다.');try{const data=await api('draft_save',{id,...candidate,expectedRevision});if(!current(gen))return;const d=data.draft;if(!d||d.id!==id||!Number.isInteger(d.revision)||d.revision<1)throw new Error('저장 응답의 초안 정보를 확인하지 못했습니다.');state.revision=d.revision;state.dirty=false;el('Saved').textContent='서버에 저장됨 · '+d.revision+'번째 저장';say('초안을 저장했습니다. 플랫폼 자료 등록은 별도로 진행합니다.','success');try{await listDrafts();}catch(_){if(current(gen))say('초안은 저장했지만 목록을 갱신하지 못했습니다. 목록 새로고침을 눌러 주세요.','warning');}}catch(e){if(!current(gen))return;if(!e.status||e.status>=500||e.status===409){state.unknown={id,expectedRevision,fingerprint:fingerprint(candidate.source,candidate.policy)};say(e.message+' 앞선 저장 결과 확인을 눌러 주세요.','warning');}else say(e.message,'error');}finally{if(current(gen))busy(false);}}
    async function reconcile(){if(state.busy||!state.unknown||!validAuth())return;const gen=state.generation,pending=state.unknown;busy(true);say('초안의 최신 저장본을 대조하고 있습니다.');try{const data=await api('draft_get',{id:pending.id});if(!current(gen))return;const d=data.draft;if(!d||d.id!==pending.id||!Number.isInteger(d.revision))throw new Error('저장본을 확인하지 못했습니다.');const doc=core.validateSource(d.source),policy=core.validatePolicy(d.policy);if(fingerprint(doc,policy)===pending.fingerprint){state.revision=d.revision;state.unknown=null;state.dirty=fingerprint(state.source,state.policy)!==pending.fingerprint;el('Saved').textContent=state.dirty?'확인 후 변경 · 저장 전':'서버 저장 확인 · '+d.revision+'번째 저장';say('앞선 저장이 반영된 것을 확인했습니다.','success');}else if(d.revision===pending.expectedRevision){state.unknown=null;say('서버는 앞선 저장 이전 상태입니다. 현재 내용을 검토하고 다시 저장할 수 있습니다.','warning');}else{say('다른 저장본이 확인되었습니다. 현재 내용을 HTML로 내려받고, 초안 목록에서 최신본을 불러와 비교해 주세요.','warning');}}catch(e){if(!current(gen))return;if(e.status===404&&pending.expectedRevision===0){state.unknown=null;say('서버에 해당 초안이 없습니다. 현재 내용을 다시 저장할 수 있습니다.','warning');}else say(e.message,'error');}finally{if(current(gen))busy(false);}}
    function filename(){const name=el('FileName').value.trim();if(!/^[A-Za-z0-9가-힣][A-Za-z0-9가-힣_.-]{0,114}\.html$/i.test(name)||name.includes('..'))throw new Error('파일명은 글자·숫자·밑줄·하이픈과 .html로 입력해 주세요.');return name;}
    async function exportHTML(register){if(state.busy||!validAuth())return;let doc,name;try{doc=validated();name=filename();}catch(e){say(e.message,'error');return;}if(register&&state.unknown){say('앞선 초안 저장 결과를 먼저 확인해 주세요.','warning');return;}const gen=state.generation;busy(true);say(register?'등록할 HTML을 만들고 있습니다.':'HTML을 만들고 있습니다.');try{const code=await runtime();if(!current(gen))return;const html=core.renderSourceHTML(doc.source,doc.policy,code);if(new Blob([html]).size>MAX_HTML)throw new Error('HTML이 3 MiB를 넘습니다. 이미지 크기나 개수를 줄여 주세요.');if(register){if(typeof window.lessonUploadFromAuthoring!=='function')throw new Error('자료 등록 연결을 확인할 수 없습니다. HTML을 내려받아 기존 자료 등록에서 선택해 주세요.');const opened=await window.lessonUploadFromAuthoring({html,fileName:name,title:doc.source.title,description:doc.source.description});if(opened!==false&&current(gen)){say('자료 등록 화면으로 보냈습니다. 제작 초안은 이 화면에 유지됩니다.');}}else{const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));state.urls.add(url);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);state.urls.delete(url);},10000);say('전체 HTML 다운로드를 요청했습니다. 이 파일을 다시 가져와 편집할 수 있습니다. 서버 초안 저장은 별도입니다.','success');}}catch(e){if(current(gen))say(e.message,'error');}finally{if(current(gen))busy(false);}}
    async function preview(){if(state.busy||!validAuth())return;let doc;try{doc=validated();}catch(e){say(e.message,'error');return;}const gen=state.generation;busy(true);try{const code=await runtime();if(!current(gen))return;let html=core.renderProtectedHTML(doc.source,doc.policy,code);const guard='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data:; connect-src \'none\'; form-action \'none\'; base-uri \'none\'"><script>window.SA_AUTHORING_PREVIEW=true;<\/script>';html=html.replace(/<head[^>]*>/i,m=>m+guard);el('PreviewFrame').srcdoc=html;el('PreviewFrame').hidden=false;el('PreviewWrap').open=true;el('PreviewNote').textContent='현재 내용의 학생 화면입니다. 미리보기 답안은 저장·제출되지 않습니다.';say('학생 화면 미리보기를 만들었습니다.');}catch(e){if(current(gen))say(e.message,'error');}finally{if(current(gen))busy(false);}}
    function beforeUnload(e){if(state.mounted&&state.dirty){e.preventDefault();e.returnValue='';}}
    async function mount(target){if(!target)return false;if(state.mounted&&host===target&&validAuth())return true;dispose();host=target;const auth=token();if(!auth){host.textContent='최고관리자로 로그인한 뒤 사용할 수 있습니다.';return false;}const next=state.generation+1;state={...freshState(),mounted:true,auth,generation:next};mountMarkup();state.source=source();state.policy=defaultPolicy();state.selected=state.source.blocks[0]?.id||null;render();window.addEventListener('beforeunload',beforeUnload);state.watch=setInterval(syncAccess,1000);const gen=state.generation;try{await loadCore();if(!current(gen))return false;render();await connect();return current(gen);}catch(e){if(current(gen))say(e.message,'error');return false;}}
    function dispose(){const old=state;if(old.watch)clearInterval(old.watch);old.requests.forEach(r=>r.abort());old.urls.forEach(url=>URL.revokeObjectURL(url));window.removeEventListener('beforeunload',beforeUnload);if(host){host.removeEventListener('input',onInput);host.removeEventListener('change',onChange);host.removeEventListener('click',onClick);host.replaceChildren();host.removeAttribute('aria-busy');}state={...freshState(),generation:old.generation+1};host=null;}
    function syncAccess(){if(state.mounted&&(!token()||token()!==state.auth))dispose();}
    window.LessonAuthoring={mount,dispose,syncAccess,canLeave};
})();
/* SCIENCE_AUTHORING_EDITOR_END */
